name: Reusable Build Workflow

on:
  workflow_call:
    secrets:
      token:
        required: true

jobs:
  build:
    name: Build and publish
    runs-on: "ubuntu-24.04"

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for GitVersion to accurately determine version

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: '5.x'

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2

      - uses: astral-sh/setup-uv@v5

      - uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Setup venv
        run: |
          uv venv
          uv sync --all-extras

      - name: Build
        run: |
          uv build
        env:
          HATCH_BUILD_HOOK_VCS_VERSION: ${{ steps.gitversion.outputs.semVer }}

      - name: Publish
        if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
        run: |
          uv publish
        env:
          UV_PUBLISH_TOKEN: ${{ secrets.token }}
